<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace DwollaSwagger\models;

use \ArrayAccess;

class AnsweredKbaQuestion implements ArrayAccess {
  static $swaggerTypes = array(
      'question_id' => 'string',
      'answer_id' => 'string'
  );

  static $attributeMap = array(
      'question_id' => 'questionId',
      'answer_id' => 'answerId'
  );


  public $question_id; /* string */
  public $answer_id; /* string */

  public function __construct(array $data = null) {
    $this->question_id = isset($data["question_id"]) ? $data["question_id"] : null;
    $this->answer_id = isset($data["answer_id"]) ? $data["answer_id"] : null;
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
