<?php
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace DwollaSwagger\models;

use \ArrayAccess;

class WebhookHttpResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'timestamp' => 'DateTime',
      'headers' => 'array[WebhookHeader]',
      'status_code' => 'int',
      'body' => 'string'
  );

  static $attributeMap = array(
      'timestamp' => 'timestamp',
      'headers' => 'headers',
      'status_code' => 'statusCode',
      'body' => 'body'
  );

  
  public $timestamp; /* DateTime */
  public $headers; /* array[WebhookHeader] */
  public $status_code; /* int */
  public $body; /* string */

  public function __construct(array $data = null) {
    $this->timestamp = $data["timestamp"];
    $this->headers = $data["headers"];
    $this->status_code = $data["status_code"];
    $this->body = $data["body"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
